Name:           ros-melodic-pyros-test
Version:        0.0.6
Release:        1%{?dist}
Summary:        ROS pyros_test package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-message-runtime >= 0.4.12
Requires:       ros-melodic-rospy >= 1.11.19
Requires:       ros-melodic-std-msgs >= 0.5.9
BuildRequires:  ros-melodic-catkin >= 0.6.18
BuildRequires:  ros-melodic-message-generation >= 0.2.10
BuildRequires:  ros-melodic-roslint >= 0.10.0
BuildRequires:  ros-melodic-rospy >= 1.11.19
BuildRequires:  ros-melodic-rostest >= 1.11.19
BuildRequires:  ros-melodic-rostopic >= 1.11.19
BuildRequires:  ros-melodic-rosunit >= 1.11.12
BuildRequires:  ros-melodic-std-msgs >= 0.5.9

%description
Basic test nodes for Pyros dynamic ROS interface

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Jun 15 2019 AlexV <asmodehn@gmail.com> - 0.0.6-1
- Autogenerated by Bloom

